updated cicd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,7 +27,6 @@ jobs:
         env:
           DATABASE_URL: sqlite:///db.sqlite3
         run: |
-          # use sqlite for CI quick tests
           python manage.py migrate --noinput
           python manage.py test --verbosity=2
 
@@ -39,21 +38,26 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Build Docker image
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         run: |
-            docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:${{ github.sha }} -f ecommerce/Dockerfile .
-            docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest
-
+          if [ -z "$DOCKER_USERNAME" ]; then
+            echo "ERROR: DOCKER_USERNAME secret is missing!"
+            exit 1
+          fi
+          docker build -t $DOCKER_USERNAME/ecommerce-app:${GITHUB_SHA::7} -f ecommerce/Dockerfile .
+          docker tag $DOCKER_USERNAME/ecommerce-app:${GITHUB_SHA::7} $DOCKER_USERNAME/ecommerce-app:latest
 
       - name: Login to DockerHub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Push images
         run: |
-          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:${{ github.sha }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:${GITHUB_SHA::7}
           docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest
 
       - name: Run Trivy scan
-        uses: aquasecurity/trivy-action@master
+        uses: aquasecurity/trivy-action@0.33.1
         with:
           image-ref: ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest
 
